### ISSUE TITLE
Button style for dark backgrounds

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#110]
The default button (https://pinecone.platform.coop/components/preview/button.html) needs a variant for dark backgrounds.

**Comment by cherylhjli** [comment]
Added to the states table, and here:

![Screen Shot 2020-01-03 at 3 09 24 PM](https://user-images.githubusercontent.com/9353905/71746507-15170600-2e3b-11ea-899a-d47a5f75c5f6.png)
