### ISSUE TITLE
Updated tag style

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#125]
**Is your feature request related to a problem? Please describe.**
Noticed that the tag style in Pinecone is a bit out of date after we adjusted the visual design on the resource detail page.

**Describe the solution you'd like**
![Screen Shot 2020-01-06 at 11 56 04 AM](https://user-images.githubusercontent.com/9353905/71833711-88a75600-307b-11ea-8565-ca420cd99881.png)
Fill: #E3EAE8
Text: #18514F

**Comment by greatislander** [comment]
@cherylhjli I noticed there's no longer a visited style for these but they still need one.
