### ISSUE TITLE
Molecule: notification

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#128]
**Is your feature request related to a problem? Please describe.**
We need a component for inline notifications (Success, Warning, Error).

**Describe the solution you'd like**
Examples:

- https://www.duetds.com/components/alert/
- https://polaris.shopify.com/components/feedback-indicators/banner#all-examples

**Describe alternatives you've considered**
Not applicable.

**Additional context**

**Comment by cherylhjli** [comment]
Updated this in the resource library component library:
https://xd.adobe.com/view/5cbb2c96-51ce-4b66-4604-15c35058ee9c-2a8a/screen/80a073de-38ab-48c5-912c-36a19939d9a2/00-Desktop-components-17

**Comment by greatislander** [comment]
@cherylhjli I think we need a neutral informational style as well.
