### ISSUE TITLE
Add "customize feed" button to home page

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#171]
## Is your feature request related to a problem? Please describe.

Adding the CTA to access the customize feed page.

## Describe the solution you'd like

A borderless button with a "customize" icon, found in the icon_v02 folder.

## Additional context

See Core screens v02 CL on the cloud for precise specs.

**Comment by greatislander** [comment]
@cherylhjli Two comments on this:

1. The order of the elements on this design is not intuitive; a screen reader user would encounter the "Customize" control before the "My Feed". I'd argue that "Customize" should be after "My Feed" to make sure that the context is clear.

2. A button is not appropriate for this; it's a link to another page, not a button that invokes an action on the current page. I'd suggest a straightforward link instead.

Thoughts?

CC: @dayotte @jhung

**Comment by dayotte** [comment]
@greatislander the Customize My Feed page has the following description: "Change what kinds of resources you see on your home page" - I think this together with any default selections (i.e. if the My Feed defaults of Most Viewed and Recently Published are selected/checked), I think it would be clear to a screenreader user what is happening. I hope I'm understanding your point correctly. I think having the persistent Customize icon in the main nav is a useful feature.

**Comment by greatislander** [comment]
I think we are talking about things slightly different, @dayotte.

Design is like this:

<img width="607" alt="Customize preceding My Feed" src="https://user-images.githubusercontent.com/605361/72848431-cef6da80-3c61-11ea-8622-63589c64f3e9.png">

What I'm suggesting is that the order should change. A screen reader user who encounters the "Customize" control before "My feed" might be missing context about what it is that they are customizing.

The change I would suggest is moving them inline so that the "Customize" control immediately follows "My feed":

<img width="608" alt="Customize following My Feed" src="https://user-images.githubusercontent.com/605361/72848560-18dfc080-3c62-11ea-9ba9-4e4dc22b645f.png">

The idea is that the title of the section should precede a control within the section.

**Comment by cherylhjli** [comment]
I tried that @greatislander, unfortunately on mobile they might very quickly run into each other, especially if it's in a language that tends towards longer words like German.
This is not running into each other, but you can imagine there are many languages we can't predict:
![Screen Shot 2020-01-21 at 6 08 33 PM](https://user-images.githubusercontent.com/9353905/72851297-408e5300-3c79-11ea-8582-3d9ea74a8f78.png)

Unless there's a way to make it bump down to the next line if the title is too long?

here are some other explorations:
![Screen Shot 2020-01-21 at 6 08 49 PM](https://user-images.githubusercontent.com/9353905/72851326-53088c80-3c79-11ea-88f2-6953650ee50c.png)
![Screen Shot 2020-01-21 at 6 09 09 PM](https://user-images.githubusercontent.com/9353905/72851335-57cd4080-3c79-11ea-82a3-e7ada71753cb.png)

**Comment by cherylhjli** [comment]
In terms of the improper use of a button, we can turn it into a link.

**Comment by greatislander** [comment]
Definitely can wrap to the next line if needed.

**Comment by cherylhjli** [comment]
Great, let's just put it next to each other per your suggestion and wrap to the next line if needed :)

**Comment by greatislander** [comment]
@cherylhjli There's one other thing we'll need to figure out, which is that our link styles have icons associated with them already, e.g.: https://pinecone.platform.coop/components/detail/link--default.html

So I'm concerned this might look a bit off. Thoughts?

**Comment by cherylhjli** [comment]
I'm thinking that if we use a link instead of a button for "customize", that we may not need to use the customize icon. What do you think?

**Comment by greatislander** [comment]
Works for me!
