### ISSUE TITLE
Links: reevaluate visited states

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#188]
**Describe the bug**

The visited state for links/calls to action is currently quite jarring.

**Comment by cherylhjli** [comment]
let's try using blue 600! subtly darker

**Comment by greatislander** [comment]
@cherylhjli What about for dark backgrounds, e.g. https://pinecone.platform.coop/components/preview/home (topics / goals / etc.)?

**Comment by greatislander** [comment]
Related: #201

**Comment by cherylhjli** [comment]
Updated states table with new visited states for tags (light), text links (light and dark). Text links (light) = blue 700), text link (dark) = blue 50
