### ISSUE TITLE
Browse all page: When filters & search term is applied

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#207]
Mockups now in VD Core Screens V02 CL folder for all viewports.

Preview:
![Screen Shot 2020-01-28 at 3 14 02 PM](https://user-images.githubusercontent.com/9353905/73301475-da598100-41e0-11ea-9194-deba6a3d79e2.png)

**Comment by greatislander** [comment]
Related: https://github.com/platform-coop-toolkit/coop-library/issues/132

CC: @dayotte @jhung
