### ISSUE TITLE
Loooong tags

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#208]
## Is your feature request related to a problem? Please describe.

Tags currently don't accommodate text that wraps beyond one line

![Screen Shot 2020-01-28 at 3 24 55 PM](https://user-images.githubusercontent.com/9353905/73302307-691acd80-41e2-11ea-9c8b-52608a415ab0.png)

**Comment by greatislander** [comment]
Related: #202
