### ISSUE TITLE
New format icons

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#211]
## Is your feature request related to a problem? Please describe.

We need some new format icons.

## Describe the solution you'd like

- [x] Academic Paper
- [x] Article
    - [ ] Journal Article
    - [ ] Magazine Article
    - [ ] Newspaper Article
    - [ ] Web Article
- [x] Audio
    - [x] Podcast
    - [ ] Radio Broadcast
- [ ] Blog Post
- [x] Book
- [x] Case Study
- [x] Curriculum
- [ ] Document
- [ ] Film
- [x] Online Training & Webinar
- [x] Presentation Slides
- [x] Report
- [ ] Software
- [ ] Template
- [ ] Thesis
- [x] Toolkit
- [x] Video

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by cherylhjli** [comment]
- Journal article, magazine article, newspaper article, web article - use generic article icon
- Radio broadcast and podcast - use generic audio icon
- Blog post - in the illustrator file (there are 2 options, I'm leaning towards the icon that looks more like an rss feed icon)
- Document - In illustrator file
- Film - use video icon
- Interview - TBH I don't think this should be a format, but if T&M push back then there's an icon in the illustrator file for it
- Software - this shouldn't be a format either, the labour platform hub is supposed to be the centralization of these software tools
- Template - in illustrator file
- Thesis - I think this is too granular to be a format, but if T&M push back then we can recycle the academic paper icon

**Comment by cherylhjli** [comment]
Illustrator file for icons: https://files.inclusivedesign.ca/s/Q4OwSPK9RYBb3SZ
