### ISSUE TITLE
Dark background colours

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#220]
## Is your feature request related to a problem? Please describe.

Currently we've assigned 3 "dark colours" that the design system can use - blue 500, blue 400, and dark mint 500. However I realized that blue 200 doesn't meet AA when on blue 400

## Describe the solution you'd like

Can we replace blue 400 with blue 600?

**Comment by greatislander** [comment]
@cherylhjli Can you clarify where this necessitates changes?
