### ISSUE TITLE
Feature: blur images without alt text

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#230]
## Is your feature request related to a problem? Please describe.

We should implement this great idea from https://github.com/hankchizljaw/modern-css-reset/pull/22.

## Describe the solution you'd like

Add a 10px blur to images with no alt tag.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by dayotte** [comment]
👍:)
