### ISSUE TITLE
Card - favourite 

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#233]
## Is your feature request related to a problem? Please describe.

Due to the amount of padding on the card for the "favourite" label, the bottom of the card appears quite large.

## Describe the solution you'd like

Is there a way to reduce the padding above the "favourite" label so that the card may look a little more proportional?

**Comment by greatislander** [comment]
Can you show me what you mean? Mark up a screenshot, maybe? https://pinecone.platform.coop/components/preview/card--resource

**Comment by greatislander** [comment]
Related: https://github.com/platform-coop-toolkit/coop-library/issues/141

**Comment by cherylhjli** [comment]
You know what, I think once we add in the date it'll look less awkward and blank.

**Comment by greatislander** [comment]
@cherylhjli The other thing to keep in mind is that with really long tags it wouldn't be able to move up without being too close to them.
