### ISSUE TITLE
Resource page updated format

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#238]
## Is your feature request related to a problem? Please describe.

Doesn't currently have all the metadata listed in the cards, carried through onto the resource page.

## Describe the solution you'd like

![](https://user-images.githubusercontent.com/9353905/74053109-28247500-49a9-11ea-82ec-d26a2381ead6.png)

Also..
- I also noticed the cards at the bottom of this page are outdated 
- Add icon for report broken link

**Comment by greatislander** [comment]
@cherylhjli What about the author byline on these? Should it be on its own line above the other metadata?

**Comment by greatislander** [comment]
I also note we are adding the date when the resource was added to the cards -- should it be here somewhere too?
