### ISSUE TITLE
Revise focus and active states for interactive elements

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#240]
## Is your feature request related to a problem? Please describe.

Follow-up to https://github.com/platform-coop-toolkit/pinecone/pull/229#issuecomment-584100497.

## Describe the solution you'd like

Implement new link and button focus and active styles as specified in XD state table.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by cherylhjli** [comment]
Updated states table with the newest focus and active states.
Components that have been updated include:
- All buttons
- All borderless buttons
- All disc buttons
- Tags
- Links
- Lists
- Accordions
- Pagination
- Checkboxes
- Radio buttons

**Comment by greatislander** [comment]
See also: https://github.com/platform-coop-toolkit/pinecone/pull/242#issuecomment-585783203
