### ISSUE TITLE
Inline link states

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#243]
## Is your feature request related to a problem? Please describe.

Currently the active state of inline links is running into the text surrounding it.

## Describe the solution you'd like

![Screen Shot 2020-02-13 at 10 22 08 AM](https://user-images.githubusercontent.com/9353905/74449618-ce112d00-4e4a-11ea-82b2-ae988a30ef86.png)

Main changes include:
- Trimming down the focus state to be extremely close to the text
- Reducing the active state double outline to 1px instead of 2

**Comment by greatislander** [comment]
I'd like to discuss this, maybe Monday after our standup?

**Comment by jhung** [comment]
Does the text get bolded when hovered, focused, or activated? It appears that is happening, but can't say for sure.

Bolding may cause shifting of text.

**Comment by jhung** [comment]
From the current design:

![image](https://user-images.githubusercontent.com/564762/80639345-df241000-8a2f-11ea-9bb8-c9eca3aaea24.png)
