### ISSUE TITLE
Inconsistent background color at Layouts -> Home

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/pinecone#246]
**Describe the bug**

At 1024px width the dark green background color at Layouts -> Home does not extend completely to the left. Mobile view loses background color entirely.

**To Reproduce**
1. Go to 'http://localhost:3000/components/detail/home'
2. Fiddle with window width.
3. See error

**Expected behavior**

Solid dark green background throughout.

**Screenshots**

![image](https://user-images.githubusercontent.com/317680/74485884-9fa64880-4e70-11ea-84fc-3a580ae6d6bc.png)

![image](https://user-images.githubusercontent.com/317680/74485905-ab920a80-4e70-11ea-8c0b-8eb607353026.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version 80.0.3987.87

**Comment by greatislander** [comment]
@erictheise Can you reproduce this here? https://pinecone.platform.coop/components/preview/home.html

**Comment by erictheise** [comment]
@greatislander, it is exactly the same, whether the left menu is expanded or hidden.

**Comment by greatislander** [comment]
Weird. Thanks for reporting.
