### ISSUE TITLE
Byline can appear inline with the resource title

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/pinecone#257]
**Describe the bug**
In a resource list, the resource byline can appear inline with the title in some situations (see image). The byline should appear in a separate line in all situations.

**To Reproduce**
1. Go to a resource listing which includes a resource with a short title (Example: "Frank Pasquale").
2. Notice the byline appears inline with the title.

**Expected behavior**
The author byline should appear in a separate line from the resource title.

**Screenshots**

![image](https://user-images.githubusercontent.com/564762/74969498-aa218e80-53ea-11ea-8a55-aecf873d9614.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium Edge

**Comment by jhung** [comment]
This issue only occurs on the home feed, specifically style `.home__feed header` is applying flex to the contents of the resource cards which is causing the title and byline to flex in their containers.

This effect can be seen by toggling `.home__feed header { display:flex; }` in the debugger.

**Comment by greatislander** [comment]
@jhung Can you open a PR for this?
