### ISSUE TITLE
Inert property when dialog is displayed is lacking a value

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/pinecone#261]
**Describe the bug**
When a dialog is visible, the `inert` property is lacking `true` value. Currently there is only `inert=""`.

**To Reproduce**
1. Go to Search Results layout
2. Select "Save my search"
3. When dialog is visible, inspect the markup.
4. Notice that the `div` containing the main content has `inert=""`.

**Expected behavior**
If a dialog is visible, the `inert` property should have value `true`. i.e. `inert="true"`.

**Comment by greatislander** [comment]
According to the [usage](https://github.com/WICG/inert#2-toggle-inert-on-an-element) for the WICG inert polyfill, the attribute can be empty. I don't think this is a bug.
