### ISSUE TITLE
Create social media and social computing icons

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/pinecone#269]
## Is your feature request related to a problem? Please describe.

Individual and organizational profiles in the map/directory/index will display a "Follow" section, which will include handles for social media such as Twitter and Instagram as well as social computing such as GitHub, Bitbucket, and StackExchange. Icons should be in the Pinecone Icon set perhaps with a bit of polish applied.

Can't easily add social media and social computing icons within a Pinecone site.

## Describe the solution you'd like

A row of common and less-common social icons in Pinecone. Someone with design skills and a good grasp of the overarching Pinecone style should collect these and make them available.

## Describe alternatives you've considered

Doing it myself.

## Additional context

![image](https://user-images.githubusercontent.com/317680/75903070-a76d6300-5e06-11ea-8d4b-7c6b4cbc3737.png)

**Comment by cherylhjli** [comment]
@greatislander what did you use on platform.coop for the social media icons? Could we recycle those?

**Comment by greatislander** [comment]
I grabbed them from https://forkaweso.me.

**Comment by greatislander** [comment]
For basic support of the directory, we need these:

- Facebook
- GitHub
- Instagram
- LinkedIn
- Medium
- Reddit
- StackExchange
- Twitter
- Mastodon (?)
