### ISSUE TITLE
Configuring default strings (for lack of a better subject)

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/pinecone#291]
Just prior to today's demo of the Directory I thought I'd change the placeholder text in the search bar from "Search resource name, publisher, or topic…" to "Search for organizations or individuals…" or something more appropriate for this context. Because Pinecone was initially developed for the Resource Library, this and possibly other texts are hardwired into Molecules and other elements.

In this case I realize that I can use a `Default` or `Inverse` Search Form rather than `Home` but I wonder if there should be a way to configure such things outside of the package so that they can survive new Pinecone releases.

**Comment by greatislander** [comment]
Molecules, etc. show example implementations. Form labels, placeholder and button texts, etc. can all be customized in implementation. The elements will all work and look as expected as long as the HTML semantics and CSS classes are maintained. I don't think what Pinecone does is that different from other frameworks. For example:

- https://get.foundation/building-blocks/blocks/searchbar-expand-on-click.html (includes placeholder text in template)
- https://getbootstrap.com/docs/4.5/components/navbar/#forms (includes placeholder text in template)

I'm closing this, if it needs to be revisited it can be reopened.
