### ISSUE TITLE
Select box down chevron should match error color

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/pinecone#312]
## Is your feature request related to a problem? Please describe.

If a select box has an error, the down chevron should match the error color. Currently it appears dark, but should be the matching error red color.

![image](https://user-images.githubusercontent.com/564762/79574009-7fbc1c80-808d-11ea-8aed-48e1bff14c52.png)

![image](https://user-images.githubusercontent.com/564762/79574034-8ba7de80-808d-11ea-8a34-9fb032f04ddc.png)

Live example:
https://deploy-preview-288--pinecone.netlify.app/components/detail/selects--default.html

## Describe the solution you'd like

The down chevron SVG should match the error color of the select box.

## Other notes

I initially tried to solve this using an SVG mask, but could not make the chevron to appear properly. It could be that the SVG mask may not work for Select input elements. More investigation may be needed.

**Comment by greatislander** [comment]
Fixed in #376.
