### ISSUE TITLE
Disabled Select input lacks a downward chevron

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/pinecone#313]
## Is your feature request related to a problem? Please describe.

Currently if a select box is disabled, the downward chevron is hidden.

![image](https://user-images.githubusercontent.com/564762/79575706-2acdd580-8090-11ea-95be-7439cb6f7dd8.png)

![image](https://user-images.githubusercontent.com/564762/79575730-315c4d00-8090-11ea-9ee8-c554fa5a3faa.png)

See live example:
https://deploy-preview-288--pinecone.netlify.app/components/detail/selects--default.html

## Describe the solution you'd like

The downward chevron should match the color of the disabled input element.

## Additional context

Because of the difficulty of using an SVG mask on a select element, the chevron is hidden to avoid any confusion for it being active.

#312 has a similar issue where the chevron is not colored properly.

**Comment by greatislander** [comment]
Fixed in #376.
