### ISSUE TITLE
After applying a top level filter, that filter appears to be unselected in filter list

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/pinecone#322]
To reproduce:
- Select and apply e.g. Topics -> Co-op Essentials (which selects all subfilters)
- After page loads the filtered content, return to filters list
- Co-op Essentials is not selected (but subfilters are), although Co-op Essentials appears in the filter tags
- tested in Firefox73 and Chrome81
<img width="1323" alt="resource library filter issue" src="https://user-images.githubusercontent.com/6207009/80002553-a48d0700-8474-11ea-9b2a-481eae00fd1b.png">

**Comment by dayotte** [comment]
@jhung could you take a look at this? @greatislander mentioned you're working on a PR that might be related, thanks

**Comment by jhung** [comment]
I've checked tag 1.0.0-rc1 and this appears to be a bug since at least that version.
