### ISSUE TITLE
Only chevrons in Nav Molecule when < large breakpoint

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/pinecone#323]
## Describe the bug

The Nav Molecule is not displaying menu choices in dropdowns.

## To Reproduce

1. Go to https://pinecone.platform.coop/components/detail/nav.html
2. Manipulate window slider until breakpoint reached and full nav bar collapses to "Menu".
3. Click Menu

## Expected behavior

Choices should be visible in the dropdown.

## Screenshots

![image](https://user-images.githubusercontent.com/317680/80149414-79d1aa00-856b-11ea-818f-d50cecde7b05.png)

## Desktop: 

 - OS:  macOS
 - Browser:  Chrome
 - Version: latest (81.0.4044.122)

**Comment by greatislander** [comment]
@erictheise Thanks for reporting this. I think it's because the nav component lacks context of the surrounding header in isolation. It works as expected in the Menu component, which positions it properly. I'm wondering if it might be a good idea not to expose the nav component by itself given that it's never supposed to be used without the surrounding menu. Thoughts?

**Comment by erictheise** [comment]
@greatislander, I'd wager that the Nav Molecule is not alone in requiring surrounding context.

What would be useful to me as a non-Pinecone core member trying to quickly implement components with minimal documentation would be to have an example of the surrounding context – everything needed to work and nothing more – with everything related to that particular component highlighted visually. Ideally there'd be non-visual cues as well.

&lt;menu&gt;
&nbsp;&nbsp;__&lt;nav&gt;
&nbsp;&nbsp;&nbsp;&nbsp;you need me for a Nav to work
&nbsp;&nbsp;&lt;/nav&gt;__
&nbsp;&nbsp;&lt;other component&gt;
&nbsp;&nbsp;&nbsp;&nbsp;you don't need me for a Nav to work but I'm highlighted on the Other Component page
&nbsp;&nbsp;&lt;/other component&gt;
&lt;/menu&gt;

So in this case, the example would have a fleshed out, working, but super-minimal Menu containing the Nav. Code for the Menu might be light grey, code for the Nav would be full strength. Any other components that depend on a surround Menu should be in there, too, but light grey, and clicking for details on those components would bring their html into full strength and the previous component (Nav here) would become light grey.

Since there are no instructions on how to build up a working component class by class, JavaScript fragment by JavaScript fragment, it would at least be useful to quickly identify a fragment that works, then copy/paste/modify it into my template partial or whatever I'm working on.
