### ISSUE TITLE
Create split dividers/<hr>s

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/pinecone#328]
## Is your feature request related to a problem? Please describe.

The [mock up for the login page](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/26) includes what appears to be a Pinecone Divider split in two with text in the center. It divides the action of logging in with a system account from logging in using a third party and contains the word __OR__ between `Divider`s.

## Describe the solution you'd like

Pinecone folks deciding what's best and providing

1. a `Split Divider` Atom in Pinecone whose options match the colors and vertical thickness of regular `Divider`s or
2. the css needed to vertically align two regular `Divider`s and horizontally center text between them or
3. html and the css to match the mock.

## Describe alternatives you've considered

Mucking around with `span`s and/or `display` myself.

## Additional context

![iPhone Login](https://user-images.githubusercontent.com/317680/80455766-349dd700-88e1-11ea-9dc9-98f68717030e.png)

**Comment by greatislander** [comment]
@dayotte Can you give me some text specifications for this? I can make the component pretty quickly as soon as I know what you have in mind for typography.

**Comment by dayotte** [comment]
![Typography](https://user-images.githubusercontent.com/6207009/80625207-bb49d580-8a01-11ea-8ac4-1cd8e647d3d8.png)

**Comment by dayotte** [comment]
@greatislander I discussed with @cherylhjli and have followed the type stack specs from the component library, you'll see the updated mobile & desktop mockups in the Account Log in / Sign up page in the Figma file here https://www.figma.com/file/tXFtpKPWuGUFrotFsXshZq/Directory-Wireframes_DA?node-id=978%3A56 
Does this give you enough or do you need more/other from me?

**Comment by greatislander** [comment]
This is perfect, thank you @dayotte!
