### ISSUE TITLE
Atom: toggle button

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#336]
## Is your feature request related to a problem? Please describe.

Toggle buttons as used in the Tool Library.

## Describe the solution you'd like

XD link to come.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by cherylhjli** [comment]
Designs: https://xd.adobe.com/view/b3e417e8-8969-4cef-4af8-41e1b53d3cae-c5d5/screen/07b2d4a5-b489-4fd6-9e33-f66589d13e76/Web-1280-1
