### ISSUE TITLE
Disabled text input form elements appear too prominent and look active

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/pinecone#361]
## Describe the bug

Disabled state is using a lighter grey than design specs - still looks like an active field.

## Screenshots

![image](https://user-images.githubusercontent.com/564762/83166727-54d9d500-a0dd-11ea-9e6a-d462cb9d58b5.png)

**Comment by greatislander** [comment]
@jhung can you clarify? I'm a bit confused by this issue; lighter would make it look less like an active field , I'd think.

**Comment by jhung** [comment]
@greatislander 
The original text from the pinecone review spreadsheet said: "_Disabled state is using a lighter grey than design specs - still looks like ean [sic] active field_"

I think just confirm the following colors while you're poking around in there:

Default Background: #F0EFEF;
Default Border: ##B2B2A7;

Inverted Background: #D5D5CF;
Inverted Border: #B2B2A7;

**Comment by greatislander** [comment]
@jhung can you open a PR for this?
