### ISSUE TITLE
Inverse accordion focus & active state colour

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#388]
## Is your feature request related to a problem? Please describe.

When working through the map view summary visual design, Dana and I found blue 200 a little overwhelming when it contains a lot of information inside, like so:

<img width="786" alt="Screen Shot 2020-06-09 at 4 55 22 PM" src="https://user-images.githubusercontent.com/9353905/84198855-2dd2ba00-aa72-11ea-8f0f-95cfa687739a.png">

## Describe the solution you'd like

Is it possible to change anywhere blue 200 appears in the inverse accordion to blue 100?
Like so:
<img width="787" alt="Screen Shot 2020-06-09 at 4 55 32 PM" src="https://user-images.githubusercontent.com/9353905/84198889-3b883f80-aa72-11ea-8eae-a184f6762cf1.png">

## Additional context

Not a high priority feature :)

**Comment by greatislander** [comment]
@jhung can perhaps address this in #380?
