### ISSUE TITLE
Hover and focus state for link with icon

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pinecone#86]
**Is your feature request related to a problem? Please describe.**
Adding a hover and focus state for link with icon (ex. "filter")

**Describe the solution you'd like**
What do you think about this, Ned?
![Screen Shot 2019-12-09 at 3 49 51 PM](https://user-images.githubusercontent.com/9353905/70471735-cb393b00-1a9b-11ea-971f-5511d743bf7b.png)

**Describe alternatives you've considered**
I know you initially described it as a "button", but upon looking at it again, I feel it's more akin to a link since it doesn't explicitly look like a button in the sense that there's a coloured box around it.

**Comment by greatislander** [comment]
Back to you for revisions as per our conversation, @cherylhjli.

**Comment by greatislander** [comment]
- [ ] @cherylhjli: review existing component at https://pinecone.platform.coop/components/detail/button.html
- [ ] @greatislander: standardize tag (view only), tag (link), tag (button) to pill shape

**Comment by cherylhjli** [comment]
![Screen Shot 2019-12-13 at 5 11 24 PM](https://user-images.githubusercontent.com/9353905/70835625-a3174800-1dcb-11ea-93f2-c8128fb8392c.png)

How's this?
This is in the XD file too.

**Comment by greatislander** [comment]
Looks good!
