### ISSUE TITLE
Add sort control

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pinecone#87]
**Is your feature request related to a problem? Please describe.**
Add sort control for resource browse view.

**Describe the solution you'd like**
TK.

**Describe alternatives you've considered**
TK.

**Additional context**
TK.

**Comment by greatislander** [comment]
@cherylhjli @dayotte Let's discuss this tomorrow? A few things I'm not sure about from the designs.

**Comment by cherylhjli** [comment]
Hey, I was playing around with the sort order issue and tried the grey line to separate the "sort by" and the applied tags and it looked pretty clunky. 
So I think what you have there right now is fine, except let's add some extra padding space between the start of the off-white block and the content, and squeeze the "sort by" in there halfway in that space:

<img width="764" alt="Screen Shot 2019-12-20 at 1 58 28 PM" src="https://user-images.githubusercontent.com/9353905/71284576-0a377e00-2331-11ea-9a7e-7aa16410b2a1.png">

Thoughts?
