### ISSUE TITLE
Opening submenu in Menu component has misleading focus styling in mobile

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/pinecone#98]
**Describe the bug**
When opening a submenu in the Menu component on mobile, the first submenu item appears to have focus, but focus is actually on the parent menu item.

**To Reproduce**
1. Go to 'Menu'
2. Resize window to mobile.
3. Open menu.
4. Using mouse or keyboard, open a submenu
5. Notice two focus styles appear - one on the parent of the submenu, and one on the first item of the submenu.

**Expected behavior**
When opening the sub menu, there should not be focus styling (or styling that would misunderstood as focus styling) on the first item.

**Screenshots**
![Annotation 2019-12-18 154249](https://user-images.githubusercontent.com/564762/71121776-1d214580-21ad-11ea-832c-3d4399af8334.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 71.0

**Comment by greatislander** [comment]
Hi @jhung — this is the active style (indicating current page) as per @cherylhjli's designs. Happy to change.

**Comment by jhung** [comment]
Something to think about @cherylhjli and @dayotte, there are 4 states: hover, focus, active, and default. It is possible that a single item, or multiple items on a page can have one or more of these states. 
For example: a link can have both Hover and Active states. Or one item can have a Hover state and a different item may have Focus, while a 3rd has Active state.

It will be good to be able to distinguish easily the different states at a glance. Clear Focus state is required for accessibility.

As a suggestion, a pattern I have used in the past that works is:
* Focus is a bold outline (keyboard users would be accustomed to this as the default browser and OS styling normally an outline)
* Hover would invert the background-foreground colour
* Active would be indicated by a flourish (a triangle, dot, checkmark, or vertical bar etc) or a different text style (i.e. bolder text)

With this pattern, each state has a visually distinct style and does not rely on colours alone to communicate its meaning (works well in monochrome and full colour).

**Comment by cherylhjli** [comment]
Great suggestion @jhung, how about something like this?
https://xd.adobe.com/view/5cbb2c96-51ce-4b66-4604-15c35058ee9c-2a8a/screen/56ec4fff-6348-4b65-b25e-f8672d976602/D-UI-Elements-2

**Comment by cherylhjli** [comment]
And maybe we can make desktop consistent like so:
<img width="848" alt="Screen Shot 2020-01-15 at 10 44 41 AM" src="https://user-images.githubusercontent.com/9353905/72447889-1bcf4280-3784-11ea-9a3a-c34ca9075ceb.png">
